-- Ritmo schema dump v1.
-- Generated by: flutter test tool/generate_schema_dump.dart
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
CREATE TABLE "audio_assets" ("id" TEXT NOT NULL, "relative_path" TEXT NOT NULL, "kind" TEXT NOT NULL, "duration_ms" INTEGER NOT NULL, "byte_size" INTEGER NOT NULL, "created_at" INTEGER NOT NULL, PRIMARY KEY ("id"), CHECK (kind IN ('day_note', 'weekly_review')), CHECK (duration_ms > 0), CHECK (byte_size > 0));

CREATE TABLE "change_initiatives" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "active" INTEGER NOT NULL DEFAULT 1 CHECK ("active" IN (0, 1)), PRIMARY KEY ("id"), CHECK (length(name) <= 120));

CREATE TABLE "checkpoint_evals" ("id" TEXT NOT NULL, "checkpoint_id" TEXT NOT NULL REFERENCES checkpoints (id), "weekly_review_id" TEXT NULL REFERENCES weekly_reviews (id), "gartner_level" TEXT NOT NULL, "notes" TEXT NULL, PRIMARY KEY ("id"), CHECK (gartner_level IN ('BD', 'B', 'I', 'A', 'E')), CHECK (notes IS NULL OR length(notes) <= 2000));

CREATE TABLE "checkpoints" ("id" TEXT NOT NULL, "cycle_id" TEXT NOT NULL REFERENCES cycles (id), "competency" TEXT NOT NULL, "date" TEXT NOT NULL, "status" TEXT NOT NULL, PRIMARY KEY ("id"), CHECK (competency IN ('ST', 'IN', 'CA')));

CREATE TABLE "contacts" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "context_note" TEXT NULL, "last_touch_date" TEXT NULL, "created_at" INTEGER NOT NULL, PRIMARY KEY ("id"), CHECK (length(name) <= 120), CHECK (context_note IS NULL OR length(context_note) <= 500));

CREATE TABLE "cycle_closure_invites" ("cycle_id" TEXT NOT NULL REFERENCES cycles (id), "week_start" TEXT NOT NULL, PRIMARY KEY ("cycle_id", "week_start"));

CREATE TABLE "cycles" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "purpose_text" TEXT NOT NULL, "start_date" TEXT NOT NULL, "end_date" TEXT NOT NULL, "state" TEXT NOT NULL, PRIMARY KEY ("id"), CHECK (length(name) <= 120), CHECK (length(purpose_text) <= 1000), CHECK (state IN ('active', 'archived')), CHECK (start_date <= end_date));

CREATE TABLE "days" ("operational_date" TEXT NOT NULL, "base_result" TEXT NOT NULL, "effective_result" TEXT NOT NULL, "closed_at" INTEGER NULL, "seal_timestamp" INTEGER NULL, "mute_cause" TEXT NULL, "previous_result" TEXT NULL, PRIMARY KEY ("operational_date"), CHECK (base_result IN ('sealed', 'unsealed')), CHECK (effective_result IN ('sealed', 'unsealed', 'mute')), CHECK (mute_cause IS NULL OR mute_cause IN ('weekend', 'holiday')), CHECK (previous_result IS NULL OR previous_result IN ('sealed', 'unsealed')), CHECK ((effective_result = 'mute') = (mute_cause IS NOT NULL)), CHECK (mute_cause IS NULL OR mute_cause <> 'holiday' OR previous_result IS NOT NULL), CHECK ((base_result = 'sealed') = (seal_timestamp IS NOT NULL)), CHECK (mute_cause IS NOT NULL OR effective_result = base_result));

CREATE TABLE "holidays" ("operational_date" TEXT NOT NULL REFERENCES days (operational_date), "active" INTEGER NOT NULL CHECK ("active" IN (0, 1)), "created_at" INTEGER NOT NULL, "removed_at" INTEGER NULL, "apply_reason_text" TEXT NULL, "remove_reason_text" TEXT NULL, PRIMARY KEY ("operational_date"), CHECK (apply_reason_text IS NULL OR length(apply_reason_text) <= 500), CHECK (remove_reason_text IS NULL OR length(remove_reason_text) <= 500));

CREATE TABLE "manifests" ("id" TEXT NOT NULL, "content_markdown" TEXT NOT NULL, "asset_version" TEXT NOT NULL, "first_copied_at" INTEGER NOT NULL, "last_edited_at" INTEGER NULL, PRIMARY KEY ("id"), CHECK (length(CAST(content_markdown AS BLOB)) <= 1048576));

CREATE TABLE "mentorships" ("id" TEXT NOT NULL, "competency" TEXT NOT NULL, "mentor_name" TEXT NULL, "last_meeting_date" TEXT NULL, PRIMARY KEY ("id"), UNIQUE ("competency"), CHECK (competency IN ('ST', 'IN', 'CA')), CHECK (mentor_name IS NULL OR length(mentor_name) <= 120));

CREATE TABLE "notification_plans" ("idempotency_key" TEXT NOT NULL, "kind" TEXT NOT NULL, "planned_at" INTEGER NOT NULL, "state" TEXT NOT NULL, PRIMARY KEY ("idempotency_key"), CHECK (kind IN ('weekly_review_sunday', 'weekly_review_monday')), CHECK (state IN ('planned', 'delivered', 'cancelled', 'suppressed')));

CREATE TABLE "pillar_entries" ("operational_date" TEXT NOT NULL REFERENCES days (operational_date), "pillar" TEXT NOT NULL, "workout_done" INTEGER NOT NULL DEFAULT 0 CHECK ("workout_done" IN (0, 1)), "briefing_done" INTEGER NOT NULL DEFAULT 0 CHECK ("briefing_done" IN (0, 1)), "briefing_mode" TEXT NULL, "workout_at" INTEGER NULL, "briefing_at" INTEGER NULL, "toggle_on" INTEGER NOT NULL DEFAULT 0 CHECK ("toggle_on" IN (0, 1)), "change_initiative_id" TEXT NULL REFERENCES change_initiatives (id), "note_text" TEXT NULL, "note_audio_id" TEXT NULL REFERENCES audio_assets (id), "night_kind" TEXT NULL, "recovery_note" TEXT NULL, "study_block_id" TEXT NULL REFERENCES study_blocks (id), UNIQUE ("operational_date", "pillar"), CHECK (pillar IN ('morning', 'day', 'night')), CHECK (briefing_mode IS NULL OR briefing_mode IN ('automatic', 'manual')), CHECK (note_text IS NULL OR length(note_text) <= 500), CHECK (night_kind IS NULL OR night_kind IN ('study', 'recovery')), CHECK (recovery_note IS NULL OR length(recovery_note) <= 500));

CREATE TABLE "pillar_waivers" ("id" TEXT NOT NULL, "date" TEXT NOT NULL REFERENCES days (operational_date), "pillar" TEXT NOT NULL, "reason_text" TEXT NOT NULL, "recurrence_confirmed" INTEGER NOT NULL DEFAULT 0 CHECK ("recurrence_confirmed" IN (0, 1)), "revoked_at" INTEGER NULL, PRIMARY KEY ("id"), CHECK (pillar IN ('morning', 'day', 'night')), CHECK (length(trim(reason_text)) > 0), CHECK (length(reason_text) <= 500));

CREATE TABLE "protocol_alarms" ("id" TEXT NOT NULL, "generation_id" TEXT NOT NULL, "start_date" TEXT NOT NULL REFERENCES days (operational_date), "end_date" TEXT NOT NULL REFERENCES days (operational_date), "sequence_length" INTEGER NOT NULL, "state" TEXT NOT NULL, "previous_state" TEXT NULL, "triggered_at" INTEGER NULL, "cause" TEXT NULL, "plan_or_execution" TEXT NULL, "adjustment" TEXT NULL, PRIMARY KEY ("id"), CHECK (sequence_length >= 2), CHECK (state IN ('pending', 'answered', 'invalidated')), CHECK (previous_state IS NULL OR previous_state IN ('pending', 'answered')), CHECK ((state = 'invalidated') = (previous_state IS NOT NULL)), CHECK (plan_or_execution IS NULL OR plan_or_execution IN ('plan', 'execution')), CHECK (cause IS NULL OR length(cause) <= 2000), CHECK (adjustment IS NULL OR length(adjustment) <= 2000), CHECK (start_date <= end_date));

CREATE TABLE "settings" ("id" INTEGER NOT NULL DEFAULT 1, "activation_date" TEXT NULL, "business_timezone" TEXT NOT NULL DEFAULT 'America/Sao_Paulo', "day_close_time_min" INTEGER NOT NULL DEFAULT 180, "night_end_time_min" INTEGER NOT NULL DEFAULT 180, "review_weekday" TEXT NOT NULL DEFAULT 'sunday', "review_time_min" INTEGER NOT NULL DEFAULT 1260, "sunday_notification_enabled" INTEGER NOT NULL DEFAULT 0 CHECK ("sunday_notification_enabled" IN (0, 1)), "sync_enabled" INTEGER NOT NULL DEFAULT 0 CHECK ("sync_enabled" IN (0, 1)), PRIMARY KEY ("id"), CHECK (id = 1), CHECK (business_timezone = 'America/Sao_Paulo'), CHECK (day_close_time_min BETWEEN 0 AND 240), CHECK (night_end_time_min BETWEEN 0 AND 1439), CHECK (review_weekday IN ('sunday', 'monday')), CHECK (review_time_min BETWEEN 0 AND 1439), CHECK ((review_weekday = 'sunday' AND review_time_min BETWEEN 1200 AND 1320) OR (review_weekday = 'monday' AND review_time_min > day_close_time_min)));

CREATE TABLE "study_blocks" ("id" TEXT NOT NULL, "operational_date" TEXT NOT NULL REFERENCES days (operational_date), "started_at" INTEGER NOT NULL, "block_deadline" INTEGER NOT NULL, "ended_at" INTEGER NULL, PRIMARY KEY ("id"), CHECK (started_at <= block_deadline), CHECK (ended_at IS NULL OR (ended_at >= started_at AND ended_at <= block_deadline)));

CREATE TABLE "weekly_contact_suggestions" ("week_start" TEXT NOT NULL, "contact_id" TEXT NOT NULL REFERENCES contacts (id), "status" TEXT NOT NULL, "created_at" INTEGER NOT NULL, UNIQUE ("week_start", "contact_id"), CHECK (status IN ('pending', 'done', 'skipped')));

CREATE TABLE "weekly_reviews" ("id" TEXT NOT NULL, "week_start" TEXT NOT NULL, "answer_fulfilled" TEXT NULL, "answer_failed" TEXT NULL, "answer_lesson" TEXT NULL, "audio_id" TEXT NULL REFERENCES audio_assets (id), "state" TEXT NOT NULL DEFAULT 'draft', "created_at" INTEGER NOT NULL, "autosaved_at" INTEGER NULL, "finalized_at" INTEGER NULL, PRIMARY KEY ("id"), UNIQUE ("week_start"), CHECK (answer_fulfilled IS NULL OR length(answer_fulfilled) <= 5000), CHECK (answer_failed IS NULL OR length(answer_failed) <= 5000), CHECK (answer_lesson IS NULL OR length(answer_lesson) <= 5000), CHECK (state IN ('draft', 'finalized')), CHECK ((state = 'finalized') = (finalized_at IS NOT NULL)));

CREATE UNIQUE INDEX cycle_one_active ON cycles(state) WHERE state = 'active';

CREATE UNIQUE INDEX initiative_one_active ON change_initiatives(active) WHERE active = 1;

CREATE UNIQUE INDEX protocol_one_live_per_generation ON protocol_alarms(generation_id) WHERE state <> 'invalidated';

CREATE INDEX protocol_pending_oldest ON protocol_alarms(start_date) WHERE state = 'pending';

CREATE UNIQUE INDEX waiver_one_active_per_day ON pillar_waivers(date) WHERE revoked_at IS NULL;

PRAGMA user_version = 1;
COMMIT;
PRAGMA foreign_keys = ON;
