import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ritmo/data/db/database.dart';

const _outputPath = 'drift_schemas/schema_v1.sql';

void main() {
  test('generate versioned schema dump', _generate);
}

Future<void> _generate() async {
  final database = RitmoDatabase(NativeDatabase.memory());
  try {
    await database.customSelect('SELECT 1').getSingle();
    final entities = await database.customSelect('''
SELECT type, name, sql
FROM sqlite_master
WHERE sql IS NOT NULL
  AND type IN ('table', 'index')
  AND name NOT LIKE 'sqlite_%'
ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name
''').get();

    final output = StringBuffer()
      ..writeln('-- Ritmo schema dump v${database.schemaVersion}.')
      ..writeln('-- Generated by: flutter test tool/generate_schema_dump.dart')
      ..writeln('PRAGMA foreign_keys = OFF;')
      ..writeln('BEGIN TRANSACTION;');
    for (final entity in entities) {
      output
        ..writeln('${entity.read<String>('sql')};')
        ..writeln();
    }
    output
      ..writeln('PRAGMA user_version = ${database.schemaVersion};')
      ..writeln('COMMIT;')
      ..writeln('PRAGMA foreign_keys = ON;');

    final target = File(_outputPath);
    await target.parent.create(recursive: true);
    await target.writeAsString(output.toString());
  } finally {
    await database.close();
  }
}
